# Use an official PostgreSQL image as a parent image
FROM postgres:latest

# Set the environment variables for PostgreSQL
ENV POSTGRES_DB=mydatabase \
    POSTGRES_USER=myuser \
    POSTGRES_PASSWORD=mypassword

# Expose the default PostgreSQL port
EXPOSE 5432
